"""Initialisation du modèle User 1

Revision ID: 0134ae860a51
Revises: 61bdd7c2b2fa
Create Date: 2025-04-08 18:18:44.439362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0134ae860a51'
down_revision: Union[str, None] = '61bdd7c2b2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
