"""mise_a_jour_des_modeles

Revision ID: c4ba68b4bf0b
Revises: 72aa02a049a6
Create Date: 2025-04-11 11:54:04.852941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ba68b4bf0b'
down_revision: Union[str, None] = '72aa02a049a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
